import type { Metadata } from 'next'
import { SeoPage, Section, LinkCard, Schema, siteSchema, websiteSchema, faqSchema, breadcrumbSchema } from '@/components/seo-page'
export const metadata: Metadata = { title: 'Saint Martin Travel Guide', description: 'A practical Saint Martin Island Bangladesh travel guide covering ships, tickets, schedule, Travel Pass, jetty and trip preparation.', alternates: { canonical: 'https://www.shiptickets.bd/saint-martin-guide' } }
const faqs: [string, string][] = [
  ['How do I plan a Saint Martin ship trip?', 'Check island open status, choose an approved ship, compare ticket class and fare, verify Travel Pass requirements, confirm the jetty and reporting time, then keep ticket details accessible for check-in.'],
  ['Which jetty departs to Saint Martin from Cox\'s Bazar?', 'Passenger vessels depart from the BIWTA Nuniachhara Jetty in Cox\'s Bazar. Verify the approved departure jetty and boarding time for your sailing date.'],
  ['Do I need a Travel Pass for Saint Martin?', 'Yes, a Travel Pass and QR-coded ticket are typically required under current government rules. Confirm the latest notice before your journey.'],
  ['How long is the ship journey to Saint Martin?', 'The Cox\'s Bazar to Saint Martin crossing takes approximately 2 hours. Sailing time varies with weather and sea conditions.'],
]
export default function GuidePage() { return <SeoPage eyebrow="Travel guide · ভ্রমণ গাইড" title="Saint Martin travel guide for ship passengers" intro="Everything starts with the right information. Use this guide to move from search to a verified ship ticket and a better-prepared journey."><Section title="The simple planning order"><p>Check whether the island is open, choose an approved ship, compare ticket class and fare, verify Travel Pass requirements, confirm the jetty and reporting time, then keep your ticket details accessible for check-in.</p></Section><div className="grid gap-4 md:grid-cols-2"><LinkCard href="/saint-martin-ship-schedule" title="Ship schedule" text="How to verify departure, return and check-in information."/><LinkCard href="/saint-martin-travel-rules" title="Travel rules" text="Seasonal access, environmental and visitor restrictions."/><LinkCard href="/routes/coxs-bazar-to-saint-martin" title="Route guide" text="Cox's Bazar to Saint Martin route planning basics."/><LinkCard href="/saint-martin-travel-pass" title="Travel Pass" text="QR ticket and authorization information."/></div><Schema data={{ '@context':'https://schema.org', '@graph':[siteSchema, websiteSchema, { '@type':'WebPage', name:'Saint Martin travel guide', isPartOf:{ '@id':'https://www.shiptickets.bd/#website' } }, faqSchema(faqs), breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Saint Martin Travel Guide' }])] }} /></SeoPage> }
