import type { Metadata } from 'next'
import { SeoPage, Section, Bullet, Status, Schema, siteSchema, websiteSchema, faqSchema, breadcrumbSchema } from '@/components/seo-page'
export const metadata: Metadata = { title: 'Saint Martin Ship Schedule', description: 'Check how to verify Saint Martin ship departure times, return schedules, check-in points and seasonal operating status.', alternates: { canonical: 'https://www.shiptickets.bd/saint-martin-ship-schedule' } }
const faqs: [string, string][] = [
  ['What time do ships depart to Saint Martin?', 'Departure times are seasonal and operator-specific. Confirm the latest departure time and check-in point for your travel date before leaving.'],
  ['How early should I arrive at the jetty?', 'Arrive at least 30 minutes before departure for check-in and boarding. Reporting time may vary by operator and season.'],
  ['Can ship schedules change due to weather?', 'Yes. Weather, tide and government permission can affect departure and return times. Confirm any changes on the day of travel.'],
  ['Is there a return sailing schedule?', 'Return sailing depends on the current season and operator. Confirm the return date, time and boarding point before booking.'],
]
export default function SchedulePage() { return <SeoPage eyebrow="Schedule · সময়সূচি" title="Saint Martin ship schedule from Cox&apos;s Bazar" intro="Ship departure and return times are seasonal and operator-specific. Here is the practical information to verify before you travel."><Section title="Current schedule status"><div className="flex flex-wrap items-center gap-3"><Status>Seasonal confirmation required</Status><span>Schedule last verified: 21 September 2026</span></div><p>Do not rely on an old departure time copied from a previous season. Confirm your operator, date, jetty and reporting time before leaving for Cox&apos;s Bazar.</p></Section><Section title="What to confirm"><ul className="grid gap-3 md:grid-cols-2"><Bullet>Departure date and reporting time</Bullet><Bullet>Designated jetty and check-in counter</Bullet><Bullet>Estimated journey duration</Bullet><Bullet>Return sailing date and time</Bullet><Bullet>Weather or tide-related changes</Bullet><Bullet>Travel Pass and QR ticket requirements</Bullet></ul></Section><Section title="Why times can change"><p>Passenger vessel operations depend on government permission, seasonal access, weather, tide and operator readiness. A responsible ticket guide shows the status clearly rather than presenting an unverified time as a promise.</p></Section><Section title="Frequently asked questions"><div className="flex flex-col gap-5">{faqs.map(([question, answer]) => <div key={question}><h3 className="font-extrabold text-[#0d1b2a]">{question}</h3><p className="text-sm leading-7 text-[#5f5e5a] mt-2">{answer}</p></div>)}</div></Section><Schema data={{ '@context':'https://schema.org', '@graph':[siteSchema, websiteSchema, { '@type':'WebPage', name:'Saint Martin Ship Schedule', isPartOf:{ '@id':'https://www.shiptickets.bd/#website' }, about:'Passenger vessel schedules to Saint Martin Island, Bangladesh' }, faqSchema(faqs), breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Saint Martin Ship Schedule' }])] }} /></SeoPage> }
