import type { Metadata } from 'next'
import { SeoPage, Section, Bullet, LinkCard, Schema, siteSchema, websiteSchema, faqSchema, breadcrumbSchema } from '@/components/seo-page'
export const metadata: Metadata = { title: "Cox's Bazar to Saint Martin Ship", description: "Understand the Cox's Bazar to Saint Martin ship route, jetty, check-in, ticket and Travel Pass information.", alternates: { canonical: 'https://www.shiptickets.bd/routes/coxs-bazar-to-saint-martin' } }
const faqs: [string, string][] = [
  ["How do I get to Saint Martin from Cox's Bazar?", 'Passenger vessels depart from the BIWTA Nuniachhara Jetty in Cox\'s Bazar during the approved tourist season. Confirm the latest departure jetty and sailing date before travel.'],
  ['How long is the journey from Cox\'s Bazar to Saint Martin?', 'The sea crossing takes approximately 2 hours. Sailing time varies with weather, tide and the specific vessel operating on your date.'],
  ['What identification do I need for the ship journey?', 'Carry valid passenger identification for check-in. Names on the ticket, Travel Pass and ID must match.'],
  ['Is there a return sailing from Saint Martin?', 'Return sailing is seasonal and operator-specific. Confirm the return date, time and check-in point at the time of booking.'],
]
export default function RoutePage() { return <SeoPage eyebrow="Route guide · রুট" title="Cox&apos;s Bazar to Saint Martin ship" intro="Plan the route with the details that matter: seasonal operating status, approved jetty, check-in time, ship class, Travel Pass and return journey."><Section title="Route overview"><p>During an approved tourist season, passenger vessels may operate between the designated Cox&apos;s Bazar jetty and Saint Martin Island. The exact vessel, departure time and access rules can change, so confirm every detail for your travel date.</p></Section><Section title="Before leaving for the jetty"><ul className="grid gap-3 md:grid-cols-2"><Bullet>Confirm the approved jetty and reporting time</Bullet><Bullet>Keep your booking reference and QR code ready</Bullet><Bullet>Carry valid passenger identification where required</Bullet><Bullet>Ask about return sailing and check-in cut-off</Bullet></ul></Section><div className="grid gap-4 md:grid-cols-2"><LinkCard href="/saint-martin-ship-ticket-price" title="Check ticket price" text="Understand one-way, return, lounge and cabin fare categories."/><LinkCard href="/saint-martin-travel-pass" title="Read Travel Pass guide" text="Verify current QR and visitor authorization requirements."/></div><Schema data={{ '@context':'https://schema.org', '@graph':[siteSchema, websiteSchema, { '@type':'TouristTrip', name:"Cox's Bazar to Saint Martin ship route", touristType:'Passenger ferry route', partOfSystem:{ '@id':'https://www.shiptickets.bd/#website' } }, faqSchema(faqs), breadcrumbSchema([{ name: 'Home', url: '/' }, { name: "Cox's Bazar to Saint Martin Ship" }])] }} /></SeoPage> }
