import Link from 'next/link'
import { ArrowRight, Check, MessageCircle, ShipWheel } from 'lucide-react'

const whatsapp = 'https://wa.me/8801700000000?text='

export function SeoPage({ eyebrow, title, intro, updated = '21 September 2026', children }: { eyebrow: string; title: string; intro: string; updated?: string; children: React.ReactNode }) {
  const pageUrl = `https://www.shiptickets.bd${typeof window === 'undefined' ? '' : window.location.pathname}`
  const pageSchema = { '@context': 'https://schema.org', '@type': 'WebPage', name: title, description: intro, url: pageUrl, isPartOf: { '@type': 'WebSite', name: 'ShipTickets.bd', url: 'https://www.shiptickets.bd' }, about: { '@type': 'Place', name: "Saint Martin's Island, Bangladesh" } }
  return <main className="min-h-screen bg-[#f7f6f2] text-[#0d1b2a]">
    <Schema data={pageSchema} />
    <div className="bg-[#0d1b2a] px-5 py-2 text-center text-xs font-semibold text-white/80">Saint Martin Island, Bangladesh · <span className="text-[#ef9f27]">Seasonal information is verified before booking</span></div>
    <header className="border-b border-[#eceae3] bg-[#f7f6f2]/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#1d9e75] text-white"><ShipWheel size={20}/></span><span><strong className="block text-lg font-extrabold tracking-tight">ShipTickets<span className="text-[#1d9e75]">.bd</span></strong><small className="block text-[10px] font-extrabold uppercase tracking-[.18em] text-[#888780]">Saint Martin made simple</small></span></Link><nav aria-label="Primary navigation" className="hidden max-w-[52vw] flex-wrap justify-end gap-x-3 gap-y-1 text-[11px] font-bold text-[#5f5e5a] md:flex sm:gap-x-5 sm:text-sm"><Link className="transition-colors hover:text-[#1d9e75]" href="/saint-martin-ship">Ships</Link><Link className="transition-colors hover:text-[#1d9e75]" href="/saint-martin-ship-ticket-price">Ticket price</Link><Link className="transition-colors hover:text-[#1d9e75]" href="/saint-martin-ship-schedule">Schedule</Link><Link className="transition-colors hover:text-[#1d9e75]" href="/saint-martin-travel-pass">Travel Pass</Link><Link className="transition-colors hover:text-[#1d9e75]" href="/saint-martin-guide">Guide</Link></nav><a aria-label="Book Saint Martin ship tickets on WhatsApp" className="shrink-0 rounded-full bg-[#1d9e75] px-3 py-2.5 text-xs font-extrabold text-white sm:px-4 sm:text-sm" href={`${whatsapp}Hello ShipTickets.bd, I need Saint Martin ship ticket information.`}>WhatsApp</a></div></header>
    <section className="mx-auto max-w-6xl px-5 pb-12 pt-14 md:pb-16 md:pt-20"><p className="mb-4 text-xs font-extrabold uppercase tracking-[.2em] text-[#1d9e75]">{eyebrow}</p><h1 className="max-w-4xl text-4xl font-extrabold leading-tight tracking-[-.04em] md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#5f5e5a]">{intro}</p><p className="mt-5 text-xs font-bold text-[#888780]">Information last reviewed: {updated}</p></section>
    <div className="mx-auto max-w-6xl px-5 pb-20"><div className="grid gap-10 lg:grid-cols-[1fr_280px]"><article className="min-w-0">{children}</article><aside className="h-fit rounded-3xl border border-[#dedcd3] bg-white p-6 lg:sticky lg:top-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#1d9e75]">Need help?</p><h2 className="mt-3 text-xl font-extrabold">Get the latest answer before you travel.</h2><p className="mt-3 text-sm leading-6 text-[#5f5e5a]">Share your date and passenger count. Our team can confirm current ship status and ticket guidance.</p><a href={`${whatsapp}Hello ShipTickets.bd, please help me with Saint Martin ship tickets.`} className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#1d9e75] px-4 py-3 text-sm font-extrabold text-white"><MessageCircle size={16}/> Ask on WhatsApp</a><Link href="/" className="mt-4 flex items-center gap-2 text-sm font-extrabold text-[#0d1b2a]">Back to homepage <ArrowRight size={15}/></Link></aside></div></div>
    <footer className="border-t border-[#eceae3] px-5 py-8 text-center text-xs text-[#888780]"><nav aria-label="Footer navigation" className="mb-4 flex flex-wrap justify-center gap-x-5 gap-y-2 font-bold text-[#5f5e5a]"><Link href="/">Home</Link><Link href="/saint-martin-ship">Ships</Link><Link href="/saint-martin-ship-ticket-price">Ticket price</Link><Link href="/saint-martin-ship-schedule">Schedule</Link><Link href="/saint-martin-travel-pass">Travel Pass</Link><Link href="/saint-martin-travel-rules">Travel rules</Link><Link href="/routes/coxs-bazar-to-saint-martin">Route guide</Link><Link href="/saint-martin-ship/keari-sindbad">Keari Sindbad</Link><Link href="/mv-karnafuly-express">MV Karnafuly Express</Link></nav><p>© 2026 ShipTickets.bd · Prices, routes and schedules are subject to current government and operator confirmation.</p></footer>
  </main>
}

export function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-10 rounded-3xl border border-[#dedcd3] bg-white p-6 md:p-8"><h2 className="text-2xl font-extrabold tracking-tight">{title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-[#5f5e5a]">{children}</div></section> }
export function Bullet({ children }: { children: React.ReactNode }) { return <li className="flex gap-3"><Check className="mt-1 shrink-0 text-[#1d9e75]" size={17}/><span>{children}</span></li> }
export function Pill({ children }: { children: React.ReactNode }) { return <span className="inline-flex rounded-full bg-[#e1f5ee] px-3 py-1 text-xs font-extrabold text-[#0f6e56]">{children}</span> }
export function Schema({ data }: { data: object }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} /> }

export const faqSchema = (items: [string, string][]) => ({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: items.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) })

export const siteSchema = { '@context': 'https://schema.org', '@type': 'Organization', name: 'ShipTickets.bd', url: 'https://www.shiptickets.bd', areaServed: 'Bangladesh', description: 'Saint Martin ship ticket information, comparison and booking support.' }

export { whatsapp }

export default function Empty() { return null }

export function Status({ children }: { children: React.ReactNode }) { return <Pill>{children}</Pill> }

export function LinkCard({ href, title, text }: { href: string; title: string; text: string }) { return <Link href={href} className="group rounded-2xl border border-[#dedcd3] bg-white p-5 transition hover:-translate-y-1 hover:border-[#1d9e75]"><h3 className="font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5f5e5a]">{text}</p><ArrowRight className="mt-4 text-[#1d9e75] transition group-hover:translate-x-1" size={17}/></Link> }
