import type { Metadata } from 'next'
import { SeoPage, Section, Bullet, Schema, siteSchema, websiteSchema, faqSchema, breadcrumbSchema } from '@/components/seo-page'
export const metadata: Metadata = { title: 'Saint Martin Travel Rules & Restrictions', description: 'A practical guide to Saint Martin Island travel rules, visitor limits, overnight stays, environmental restrictions and ship ticket checks.', openGraph: { title: 'Saint Martin Travel Rules & Restrictions Guide', description: 'Learn the current travel rules, visitor limits, environmental restrictions and ticket checks for Saint Martin Island.', images: [{ url: '/og_image.png', width: 1200, height: 630 }] }, alternates: { canonical: 'https://www.shiptickets.bd/saint-martin-travel-rules' } }
const faqs: [string, string][] = [
  ['What are the Saint Martin travel rules?', 'Rules vary by season and government notice. Verify island access, visitor limits, Travel Pass requirements, approved vessels and environmental restrictions before travel.'],
  ['Can I visit Saint Martin right now?', 'Island access depends on the current government-approved season, visitor limit and operator permissions. Confirm the open status for your planned date before booking.'],
  ['What is the daily visitor limit for Saint Martin?', 'The daily visitor limit varies by season and government rules. Confirm the current limit for your travel date before planning your trip.'],
  ['Can I stay overnight on Saint Martin Island?', 'Overnight stays have separate limits and rules that change by season. Confirm overnight permissions before booking accommodation.'],
  ['Are there environmental restrictions on Saint Martin?', 'Yes. Plastic restrictions, coral protection rules and designated activity zones are enforced. Follow local authority instructions.'],
]
export default function RulesPage() { return <SeoPage eyebrow="Rules · ভ্রমণ নির্দেশনা" title="Saint Martin travel rules and restrictions" intro="Saint Martin Island access is seasonal and regulated. Check current rules before booking a ship ticket, hotel or transport plan."><Section title="Can I visit Saint Martin now?"><div className="mb-6 rounded-2xl border border-[#d4e6e2] bg-white p-5 shadow-[0_4px_20px_rgba(18,60,69,.06)]"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#1d9e75]">Quick Answer</p><p className="mt-2 text-sm leading-6 text-[#5f5e5a]">Saint Martin Island access is seasonal and regulated by government rules. The island is typically closed February–October and reopens around November with a 2,000 daily visitor limit. A Travel Pass and QR-coded ticket are required during the tourist season. Plastic restrictions, coral protection rules and designated activity zones are enforced. Always confirm the current open status, visitor limits and rules for your planned travel date before booking.</p></div><p>Access depends on the current government-approved season, visitor limit and operator permissions. Treat every schedule and ticket as subject to confirmation.</p></Section><Section title="Rules to verify before travel"><ul className="grid gap-3 md:grid-cols-2"><Bullet>Whether the island is open for tourism</Bullet><Bullet>Daily visitor and overnight stay limits</Bullet><Bullet>Travel Pass and QR ticket requirements</Bullet><Bullet>Approved jetty and vessel list</Bullet><Bullet>Environmental protections and restricted items</Bullet><Bullet>Weather and sea-condition notices</Bullet></ul></Section><Section title="Travel responsibly"><p>Saint Martin is a sensitive marine environment. Follow local authority instructions, avoid single-use plastic where restricted, do not damage coral or wildlife, and keep the beach and jetty clean.</p></Section><Schema data={{ '@context':'https://schema.org', '@graph':[siteSchema, websiteSchema, faqSchema(faqs), breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Saint Martin Travel Rules' }])] }} /></SeoPage> }
