import type { Metadata } from 'next'
import { SeoPage, Section, Bullet, Schema, siteSchema, websiteSchema, faqSchema, breadcrumbSchema } from '@/components/seo-page'
export const metadata: Metadata = { title: 'Saint Martin Travel Pass & QR Ticket', description: 'Learn what the Saint Martin Travel Pass and QR-coded ship ticket mean, why they matter and what to verify before travel.', alternates: { canonical: 'https://www.shiptickets.bd/saint-martin-travel-pass' } }
const faqs: [string,string][] = [
  ['What is the Saint Martin Travel Pass?', 'It is the travel authorization or pass used under the applicable government rules for visitors to Saint Martin Island. Requirements can change by season.'],
  ['Do I need a QR-coded ticket?', 'If current rules require a QR-coded ticket or Travel Pass, use only a valid ticket issued through an authorized process and verify the details before departure.'],
  ['How do I apply for a Travel Pass?', 'Travel Pass requirements are managed by the applicable authorities. Confirm the latest process with an authorized ticketing channel before your travel date.'],
  ['Do I need a separate Travel Pass if I have a ship ticket?', 'The Travel Pass and ship ticket rules are separate. Check whether a separate visitor authorization is required alongside your ship ticket before booking.'],
  ['What if my name is misspelled on the Travel Pass?', 'Request a correction before departure. Some authorities require name changes to be resolved before check-in.'],
]
export default function TravelPassPage() { return <SeoPage eyebrow="Travel Pass · ট্রাভেল পাস" title="Saint Martin Travel Pass and QR ticket guide" intro="A ship ticket is not the only thing to check. Understand the Travel Pass, QR code and current visitor rules before planning your Saint Martin trip."><Section title="The short answer"><p>Travel Pass and QR ticket rules are controlled by the applicable authorities and can change between seasons. Confirm the latest notice and make sure your passenger details match the ticket.</p></Section><Section title="Before departure"><ul className="grid gap-3"><Bullet>Use an authorized ticketing channel.</Bullet><Bullet>Check passenger name, date, ship and route.</Bullet><Bullet>Keep the QR code accessible on your phone and carry a backup where appropriate.</Bullet><Bullet>Ask what happens if the sailing or government access rules change.</Bullet></ul></Section><Section title="Avoid unofficial tickets"><p>Do not pay for a screenshot, incomplete booking reference or ticket that does not identify the operator and passenger. A clear support team should explain the ticket, fare, check-in and cancellation conditions.</p></Section><Schema data={{ '@context':'https://schema.org', '@graph':[siteSchema, websiteSchema, faqSchema(faqs), breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Saint Martin Travel Pass' }])] }} /></SeoPage> }
